### ISSUE TITLE
QB logs broken

### ISSUE THREAD

**Issue by R1M0INC** [qbcore-framework/qb-smallresources#217]
Half the logs do not work correctly also in the inventory logs when ever you left click it will spam the logs with random data

**Comment by xenfovn** [comment]
change it to slack

**Comment by nzkfc** [comment]
Also having this isuse, some logs like drop/stash/player inventory don't seem to log everything. Was fine when we ran qb-logs but since using the one where it moves to qb-smallresources it's started to play up.

**Comment by BerkieBb** [comment]
> like drop/stash/player inventory

In the SetInventory log?

**Comment by nzkfc** [comment]
> > like drop/stash/player inventory
> 
> In the SetInventory log?

Yeah, but I think it's just discord rate limiting due to the sheer number of logs. Players make tickets all the time due to qb-inventory bug where items dragged and dropped sometimes (usually the first item when you first open a stash and move over) disapearing (they drop instead of going into stash/trunk etc) and we go to check the logs and we can't see it, but they have a clip of doing it.

I really think it's a rate limit thing on discord though.

**Comment by BerkieBb** [comment]
I think the same as nothing really was just changed to the logs itself

**Comment by nzkfc** [comment]
Yeah,  it happens since qb logs went into small resources we noticed,  but
there's a crap ton of logs,  we might cut back or push them to slack instead

**Comment by BerkieBb** [comment]
Yeah discord is not a great place for logs

**Comment by coba59** [comment]
i have the same issue with the logs. some fix or help to fix it?
